name: Test
on:
  pull_request:
  push:
    branches:
      - main

env:
  otp-version: 24.3
  elixir-version: 1.13.3
  node-version: 16.18

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}

      - name: Cache mix dependencies
        uses: actions/cache@v3
        env:
          cache-name: mix
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.otp-version }}-${{ env.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.otp-version }}-${{ env.elixir-version }}-

      - name: Install mix dependencies
        run: |
          mix deps.get
          mix deps.unlock --check-unused

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check compile warnings
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install npm dependencies
        run: npm ci --prefix assets

      - name: Check assets formatting
        run: npm run format-check --prefix assets
